[PIN-1677] Adding limitations to strings fields inside yml
pagopa/interop-be-purpose-process pull request #130
Opened 2023-01-23 15:12 UTC by bloodsky

2023-01-23 15:51 UTC, TonioGela approved these changes

2023-01-25 08:04 UTC, galales requested changes

2023-01-25 08:04 UTC, galales commented on src/main/resources/interface-specification.yml
> +              minLength: 10
Our enum values may be shorter

```suggestion
              minLength: 1
```

2023-01-26 11:36 UTC, galales approved these changes

2023-01-26 12:15 UTC, merged