PIN-1377 Create endpoint and service
pagopa/interop-be-purpose-process pull request #139
Opened 2023-02-22 14:42 UTC by nttdata-rtorsoli

2023-02-24 09:14 UTC, galales requested changes

2023-02-24 09:14 UTC, galales commented on src/main/scala/it/pagopa/interop/purposeprocess/api/impl/PurposeApiServiceImpl.scala
> +    authorize(ADMIN_ROLE, API_ROLE, SECURITY_ROLE) {
Write operations on purposes can be done only by admins
```suggestion
    authorize(ADMIN_ROLE) {
```

2023-02-24 09:14 UTC, galales commented on src/main/scala/it/pagopa/interop/purposeprocess/api/impl/PurposeApiServiceImpl.scala
> +        val latestAll: Option[Int] = versions.sortBy(s => s.createdAt)(ordering).map(_.dailyCalls).headOption
```suggestion
        val latestAll: Option[Int] = versions.sortBy(_.createdAt)(ordering).map(_.dailyCalls).headOption
```

2023-02-24 09:14 UTC, galales commented on src/main/scala/it/pagopa/interop/purposeprocess/api/impl/PurposeApiServiceImpl.scala
> +  override def clonePurpose(purposeId: String)(implicit
this endpoint needs to be tested with the `authz` test

2023-02-24 09:14 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeApiServiceSpec.scala
> +            state = PurposeManagementDependency.PurposeVersionState.SUSPENDED,
Just to have a more realistic case (only one version in a purpose can be ACTIVE or SUSPENDED in a given time)
```suggestion
            state = PurposeManagementDependency.PurposeVersionState.ARCHIVED,
```

2023-02-24 09:14 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeApiServiceSpec.scala
> +    "succeed" in {
```suggestion
    "succeed when there is only a WAITING FOR APPROVAL version" in {
```

2023-02-24 09:14 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeApiServiceSpec.scala
> +    "succeed with multiple versions latest is WAITING FOR APPROVAL" in {
```suggestion

    "succeed with multiple versions when latest is WAITING FOR APPROVAL" in {
```

2023-02-24 09:14 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeApiServiceSpec.scala
> +    "succeed with multiple versions no WAITING FOR APPROVAL" in {
```suggestion

    "succeed with multiple versions when there is no WAITING FOR APPROVAL" in {
```

2023-02-24 09:14 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeApiServiceSpec.scala
> +    "succeed with check of new purpose title" in {
```suggestion

    "succeed with check of new purpose title" in {
```

2023-02-24 09:14 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeApiServiceSpec.scala
> +    "fail if Purpose does not exist" in {
```suggestion

    "fail if Purpose does not exist" in {
```

2023-02-24 14:32 UTC, TonioGela approved these changes

2023-02-27 15:23 UTC, galales approved these changes

2023-02-27 15:26 UTC, merged