Pin 2877 [BE] Non dovrebbe essere possibile creare e pubblicare una finalità su una richiesta di fruizione in stato SUSPENDED
pagopa/interop-be-purpose-process pull request #143
Opened 2023-04-05 10:40 UTC by nttdata-rtorsoli

2023-04-05 13:21 UTC, TonioGela approved these changes

2023-04-05 14:41 UTC, galales requested changes
nice and clean change, just minor changes

2023-04-05 14:41 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeVersionStateSpec.scala
> +// import it.pagopa.interop.agreementmanagement.client.{model => AgreementManagement}
🧹

2023-04-05 14:41 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/PurposeVersionStateSpec.scala
> +        problem.status shouldBe StatusCodes.Forbidden.intValue
for consistency this should return a bad request

2023-04-05 14:41 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/SpecHelper.scala
> +  def mockVersionLoadValidationFailed(
```suggestion
  def mockVersionLoadValidationAgreementNotFound(
```

2023-04-06 09:24 UTC, galales approved these changes

2023-04-11 10:28 UTC, merged