PIN-3325 [BE] Aggiornare la configurazione dell'analisi di rischio dei privati
pagopa/interop-be-purpose-process pull request #154
Opened 2023-05-03 15:31 UTC by nttdata-rtorsoli

2023-05-04 07:51 UTC, galales requested changes

2023-05-04 07:51 UTC, galales commented on src/main/resources/riskAnalysisTemplate/forms/PRIVATE/2.0.json
the given risk analysis is the 1.0 for PRIVATE

2023-05-04 07:51 UTC, galales commented on src/test/scala/it/pagopa/interop/purposeprocess/RiskAnalysisValidationSpec.scala
> -    "succeed on correct form 1.0" in {
⚠️ this was the test for the version 1.0 for PAs, it should not be migrated to 2.0.
The test for the PAs 2.0 should be a different test

2023-05-04 07:51 UTC, galales commented on src/test/resources/riskAnalysisTemplate/forms/PRIVATE/2.0.json
same for other PR, this should not be duplicated in test package

2023-05-04 10:26 UTC, nttdata-rtorsoli commented on src/main/resources/riskAnalysisTemplate/forms/PRIVATE/2.0.json
?

2023-05-04 13:28 UTC, galales approved these changes

2023-05-08 07:28 UTC, beetlecrunch approved these changes

2023-05-09 12:13 UTC, galales approved these changes

2023-05-09 12:57 UTC, merged