PIN-4057: added eServiceMode flag on riskAnalysis
pagopa/interop-be-purpose-process pull request #183
Opened 2023-10-03 14:47 UTC by AsterITA

2023-10-04 09:05 UTC, galales requested changes

2023-10-04 09:05 UTC, galales commented on src/main/scala/it/pagopa/interop/purposeprocess/api/impl/PurposeVersionActivation.scala
> +        },
the `EServiceInfo` should keep the information as enum, labels are confined to the generated document.
The `PDFCreatorImpl` should be in charge of assigning the corresponding label.
Also, because the document can be generated in different languages

2023-10-04 12:17 UTC, galales approved these changes
LGTM, english translations need to be validated with @ruggerocastagnola

2023-10-05 08:15 UTC, AsterITA commented
> LGTM, english translations need to be validated with @ruggerocastagnola

He approved the new translation I just pushed

2023-10-09 12:19 UTC, beetlecrunch approved these changes

2023-10-24 07:57 UTC, merged