BKE - Update of daily calls  with the same value of the previous version is not allowed
pagopa/interop-be-purpose-process pull request #196
Opened 2024-01-09 11:32 UTC by nttdata-rtorsoli

2024-01-09 13:57 UTC, galales requested changes
this feature is not related to `updatePurpose` and `updateReversePurpose` paths, but to `createPurposeVersion`.
Updating a draft purpose is always allowed, the issue arise when creating a new version that has the same dailyCalls as the previous

2024-01-10 10:56 UTC, galales reviewed
minor points

2024-01-10 10:56 UTC, galales commented on src/main/scala/it/pagopa/interop/purposeprocess/api/impl/PurposeApiServiceImpl.scala
> +      case _                          => Future.failed(DailyCallsEqualThanBefore(purpose.id))
albeit similar, with this change we cover exactly the case we need (while leaving the absence of versions a responsibility of other checks)
```suggestion
      case Some(x) if x == dailyCalls => Future.failed(DailyCallsEqualThanBefore(purpose.id))
      case _                          => Future.successful(())
```

2024-01-10 10:56 UTC, galales commented on src/main/scala/it/pagopa/interop/purposeprocess/error/PurposeProcessErrors.scala
> +      extends ComponentError("0028", s"Purpose $purposeId has the same dailyCalls")
minor readability improvement
```suggestion
  final case class UnchangedDailyCalls(purposeId: UUID)
      extends ComponentError("0028", s"Creation of new version without changing daily calls for purpose $purposeId")
```

2024-01-11 10:17 UTC, galales approved these changes
🚀

2024-01-11 14:09 UTC, beetlecrunch approved these changes

2024-01-15 11:25 UTC, merged